### ISSUE TITLE
calfw not work

### ISSUE THREAD

**Issue by ZucchiniY** [appleshan/my-spacemacs-config#2]
您好，我在spacemacs 中，增加了 calfw 的配置，但是在使用的时候，M-x 找不到 cfw:open-calendar-buffer, 这个命令，但是查看 elpa 的时候，是能找到 calfw 的 package 的，请问您的配置能正常使用这个 package 吗？

Message：
command-execute: Wrong type argument: commandp, cfw:open-calendar-buffer

**Comment by appleshan** [comment]
可以。

我这边的calfw 的配置被注释关闭了：
https://github.com/appleshan/my-spacemacs-config/blob/master/layers/appleshan-org/packages.el#L14

如果开启，然后 M-x 能找到 cfw:open-calendar-buffer 。

**Comment by ZucchiniY** [comment]
好的，非常感谢~
